apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: exam-lucasdriessens
  labels:
    createdBy: 'Nathan-Segers'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api # Change this to match the label in the template
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: lucasdriessens/container_api:latest
          imagePullPolicy: IfNotPresent
          name: api
          ports:
            - containerPort: 8080
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: configmaplucas
                  key: NAME
            - name: DATE
              valueFrom:
                configMapKeyRef:
                  name: configmaplucas
                  key: DATE
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: configmaplucas

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api # This should match the label in the Deployment's pod template
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30001
